//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.02 at 10:14:35 AM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/student/")
package com.hazelnutprogramming.objects;
